# Generated by Django 5.1.7 on 2025-04-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staff_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notifications',
            name='status',
        ),
    ]
