# Generated by Django 5.1.7 on 2025-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_staff_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notifications',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
